# Generated by Django 3.2.3 on 2021-05-26 11:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_auto_20210526_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User'},
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(limit_value=10)])),
                ('task_description', models.CharField(max_length=2000)),
                ('task_pic', models.FileField(blank=True, null=True, upload_to='tasks/')),
                ('create_time_stamps', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
