# Generated by Django 3.2.3 on 2021-05-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_auto_20210526_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
