# Generated by Django 3.2.3 on 2021-05-26 23:38

from django.db import migrations, models
import user_task.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_pic',
            field=models.FileField(blank=True, null=True, upload_to=user_task.models.task_upload_location),
        ),
    ]
